// ============================================================
// Project Engine Tool — محرك بناء المشروع الحقيقي
// ------------------------------------------------------------
// يطبق دورة كاملة: تحليل الطلب → خطة → إنشاء ملفات → تنفيذ → تحقق
// ثم يخرج المشروع داخل built_projects/<slug>_<timestamp>/ في مساحة العمل.
// ============================================================

import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { cloudBridge } from './ai_bridge.js';

const projectIntentRegex = /(أنشئ|أنشأ|اصنع|أنشِئ|ابني|أبني|بني|صمم|تصميم|معمارية|build|create|generate|scaffold|make|مشروع|project|تطبيق|واجهة|موقع|website|dashboard|api)/i;
const projectTopicRegex = /(مشروع|project|موقع|website|واجهة|ui|dashboard|app|تطبيق|api|backend|bot|landing|صفحة|site|هيكل|ملفات|مجلدات)/i;

function slugify(value) {
    return String(value || 'suras-project')
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\u0600-\u06FF\s-]+/g, '')
        .replace(/[\s_]+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 40) || 'suras-project';
}

function hashText(value) {
    let hash = 2166136261;
    for (const char of String(value || '')) {
        hash ^= char.codePointAt(0);
        hash = Math.imul(hash, 16777619);
    }
    return Math.abs(hash >>> 0);
}

function extractProjectName(query) {
    const cleaned = String(query || '')
        .replace(/(?:اريد|أريد|ابغى|أبغى|بدي|عايز|عاوز|احتاج|أحتاج|من فضلك|لو سمحت)/gi, ' ')
        .replace(/(?:انشئ|أنشئ|اصنع|ابني|أبني|بني|صمم|تصميم|اعمل|سوي|سويلي|لي|لنا|مشروع|project|build|create|generate|make)/gi, ' ')
        .replace(/\s+/g, ' ')
        .trim();
    return cleaned || 'suras-project';
}

function baseBuiltProjectsDir(rootDir = process.cwd()) {
    return path.join(path.resolve(rootDir, '..'), 'built_projects');
}

function inferProjectType(query) {
    const text = String(query || '').toLowerCase();
    if (/(api|backend|server|express|rest|endpoint)/i.test(text)) return 'node-api';
    if (/(dashboard|لوحة|admin|panel)/i.test(text)) return 'dashboard';
    if (/(bot|assistant|chat|conversation)/i.test(text)) return 'chat-app';
    return 'static-web';
}

function writeFileSafe(filePath, content) {
    const dir = path.dirname(filePath);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, content, 'utf-8');
}

function makeReadme(projectName, projectType) {
    return `# ${projectName}\n\nتم إنشاء هذا المشروع بواسطة Suras Project Engine.\n\n## النوع\n${projectType}\n\n## التشغيل\n\n1. افتح المجلد \n2. شغّل الأمر المناسب\n3. استخدم المعاينة المحلية\n\n## ملاحظات\n- تم إنشاء المشروع داخل built_projects\n- تم تطبيق دورة بناء + تحقق قبل التسليم\n`;
}

function makeNodeApiProject(projectName, projectDir) {
    const serverCode = `import express from 'express';\n\nconst app = express();\nconst port = process.env.PORT || 3000;\n\napp.use(express.json());\n\napp.get('/health', (req, res) => {\n  res.json({ status: 'ok', service: '${projectName}', timestamp: new Date().toISOString() });\n});\n\napp.get('/', (req, res) => {\n  res.json({\n    app: '${projectName}',\n    message: 'API جاهزة',\n    routes: ['/health']\n  });\n});\n\napp.listen(port, () => {\n  console.log('Server running on http://localhost:' + port);\n});\n`;

    const packageJson = `{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "${projectName} generated by Suras",
  "type": "module",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^5.2.1"
  }
}\n`;

    const files = [
        { path: path.join(projectDir, 'package.json'), content: packageJson },
        { path: path.join(projectDir, 'server.js'), content: serverCode },
        { path: path.join(projectDir, 'README.md'), content: makeReadme(projectName, 'node-api') },
    ];

    for (const f of files) writeFileSafe(f.path, f.content);
    return files.map((f) => f.path);
}

function makeStaticWebProject(projectName, projectDir, requestText = projectName) {
    const palettes = [
        ['#07111f', '#10243b', '#2563eb', '#22d3ee'],
        ['#1a1020', '#2b1730', '#db2777', '#f59e0b'],
        ['#0b1712', '#142a20', '#16a34a', '#a3e635'],
        ['#111126', '#211b3d', '#7c3aed', '#c4b5fd'],
    ];
    const [bg, card, primary, accent] = palettes[hashText(requestText) % palettes.length];
    const messages = ['حل عملي يبدأ من احتياجك الحقيقي.', 'تجربة واضحة، سريعة، ومصممة للنمو.', 'كل التفاصيل مرتبة لتصل إلى النتيجة أسرع.', 'واجهة هادئة تترك التركيز للمحتوى.'];
    const message = messages[hashText(`${requestText}:message`) % messages.length];
    let html = `<!DOCTYPE html>\n<html lang="ar" dir="rtl">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${projectName}</title>\n    <link rel="stylesheet" href="styles.css" />\n  </head>\n  <body>\n    <main class="shell">\n      <section class="hero">\n        <span class="tag">Suras Project</span>\n        <h1>${projectName}</h1>\n        <p>تم إنشاء هذا المشروع داخل Suras بواسطة محرك بناء المشروع الذاتي.</p>\n        <button id="actionBtn">ابدأ الآن</button>\n      </section>\n    </main>\n    <script src="app.js"></script>\n  </body>\n</html>\n`;

    html = html
        .replace('<main class="shell">', `<main class="shell variant-${hashText(requestText) % 4}">`)
        .replace('<span class="tag">Suras Project</span>', '<span class="tag">مشروع جديد من Suras</span>')
        .replace('تم إنشاء هذا المشروع داخل Suras بواسطة محرك بناء المشروع الذاتي.', message)
        .replace('ابدأ الآن', 'ابدأ التجربة')
        .replace('</section>\n    </main>', '</section>\n      <aside class="feature-card"><strong>مصمم لهذا الطلب</strong><span>تم إنشاء هوية مستقلة وبنية جديدة لهذا المشروع.</span></aside>\n    </main>');

    const css = `:root {\n  --bg: ${bg};\n      --card: ${card};\n  --primary: ${primary};\n  --accent: ${accent};\n  --text: #edf2ff;\n}\n\n* { box-sizing: border-box; }\nbody {\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: radial-gradient(circle at top, #1e293b, var(--bg));\n  color: var(--text);\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n}\n.shell { width: min(900px, 90vw); }\n.hero {\n  background: rgba(18, 26, 45, 0.9);\n  border: 1px solid rgba(255,255,255,0.08);\n  padding: 48px;\n  border-radius: 20px;\n  box-shadow: 0 20px 50px rgba(0,0,0,0.35);\n}\n.tag {\n  display: inline-block;\n  background: rgba(124,58,237,0.15);\n  color: var(--accent);\n  padding: 8px 12px;\n  border-radius: 999px;\n  font-size: 12px;\n  letter-spacing: 1px;\n}\nh1 { font-size: clamp(2rem, 5vw, 4rem); margin: 20px 0; }\np { font-size: 1.1rem; color: rgba(237,242,255,0.8); }\nbutton {\n  margin-top: 18px;\n  border: none;\n  background: linear-gradient(135deg, var(--primary), var(--accent));\n  color: white;\n  padding: 14px 22px;\n  border-radius: 12px;\n  font-size: 1rem;\n  cursor: pointer;\n}\n`;

    const enhancedCss = `.shell { width: min(1080px, 90vw); display:grid; grid-template-columns: 1.4fr .8fr; gap:24px; align-items:stretch; }\n.feature-card { background: var(--card); border: 1px solid rgba(255,255,255,.1); border-radius: 20px; padding: 28px; display:flex; flex-direction:column; justify-content:flex-end; min-height:220px; }\n.feature-card strong { color: var(--accent); font-size: 1.5rem; margin-bottom: 10px; }\n.feature-card span { color: rgba(237,242,255,.65); }\n.variant-1 .hero { border-radius: 4px 36px 4px 36px; }\n.variant-2 .hero { text-align: center; }\n.variant-3 .hero, .variant-3 .feature-card { border-radius: 4px; }\n@media (max-width: 720px) { .shell { grid-template-columns: 1fr; } .feature-card { min-height: 140px; } }\n`;
    const js = `document.getElementById('actionBtn')?.addEventListener('click', () => {\n  alert('تم تشغيل المشروع بنجاح.');\n});\n`;

    const files = [
        { path: path.join(projectDir, 'index.html'), content: html },
        { path: path.join(projectDir, 'styles.css'), content: css + enhancedCss },
        { path: path.join(projectDir, 'app.js'), content: js },
        { path: path.join(projectDir, 'README.md'), content: makeReadme(projectName, 'static-web') },
    ];

    for (const f of files) writeFileSafe(f.path, f.content);
    return files.map((f) => f.path);
}

function makeDashboardProject(projectName, projectDir, requestText = projectName) {
    const dashboardPalettes = [
        ['#0f172a', '#111827', '#a5b4fc'],
        ['#1c1024', '#2b1538', '#f9a8d4'],
        ['#0b1b18', '#12332a', '#86efac'],
        ['#171326', '#292044', '#c4b5fd'],
    ];
    const [dashboardBg, dashboardSide, dashboardAccent] = dashboardPalettes[hashText(requestText) % dashboardPalettes.length];
    const html = `<!DOCTYPE html>\n<html lang="ar" dir="rtl">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${projectName}</title>\n  <link rel="stylesheet" href="styles.css" />\n</head>\n<body>\n  <div class="layout">\n    <aside class="sidebar">\n      <h2>${projectName}</h2>\n      <nav>\n        <a href="#">الرئيسية</a>\n        <a href="#">التحليلات</a>\n        <a href="#">المهام</a>\n      </nav>\n    </aside>\n    <main class="main">\n      <div class="cards">\n        <div class="card"><span>الطلبات</span><strong>128</strong></div>\n        <div class="card"><span>المبيعات</span><strong>42K</strong></div>\n        <div class="card"><span>الزوار</span><strong>8.4K</strong></div>\n      </div>\n    </main>\n  </div>\n  <script src="app.js"></script>\n</body>\n</html>\n`;

    const css = `body { margin: 0; font-family: Arial, sans-serif; background: ${dashboardBg}; color: white; }\n.layout { display:flex; min-height:100vh; }\n.sidebar { width: 220px; background:${dashboardSide}; padding:24px; }\n.main { flex:1; padding:30px; }\n.cards { display:grid; grid-template-columns:repeat(3,minmax(150px,1fr)); gap:20px; }\n.card { background:rgba(255,255,255,.08); padding:20px; border-radius:14px; border:1px solid rgba(255,255,255,.08); }\n.card span { display:block; color:${dashboardAccent}; }\n.card strong { font-size: 2rem; display:block; margin-top:8px; }\n`;

    const js = `console.log('${projectName} dashboard ready');\n`;

    const files = [
        { path: path.join(projectDir, 'index.html'), content: html },
        { path: path.join(projectDir, 'styles.css'), content: css },
        { path: path.join(projectDir, 'app.js'), content: js },
        { path: path.join(projectDir, 'README.md'), content: makeReadme(projectName, 'dashboard') },
    ];

    for (const f of files) writeFileSafe(f.path, f.content);
    return files.map((f) => f.path);
}

function projectFilesByType(type, projectName, projectDir, requestText) {
    if (type === 'node-api') return makeNodeApiProject(projectName, projectDir);
    if (type === 'dashboard') return makeDashboardProject(projectName, projectDir, requestText);
    if (type === 'chat-app') return makeStaticWebProject(projectName, projectDir, requestText);
    return makeStaticWebProject(projectName, projectDir, requestText);
}

function spawnAsync(command, args, options = {}) {
    return new Promise((resolve) => {
        const child = spawn(command, args, { ...options, shell: false });
        let stdout = '';
        let stderr = '';
        child.stdout.on('data', (chunk) => { stdout += chunk.toString(); });
        child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
        child.on('close', (code) => resolve({ code: code ?? 1, stdout, stderr }));
        child.on('error', (error) => resolve({ code: 1, stdout, stderr: `${stderr}${error.message}` }));
    });
}

async function verifyProject(projectDir) {
    const checks = [];
    const files = [];
    const walk = (dir) => {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory()) walk(fullPath);
            else files.push(fullPath);
        }
    };
    walk(projectDir);

    const jsFiles = files.filter((file) => file.endsWith('.js'));
    for (const file of jsFiles) {
        const result = await spawnAsync('node', ['--check', file], { cwd: projectDir });
        const ok = result.code === 0;
        checks.push({ file: path.relative(projectDir, file), check: 'node --check', ok, output: (result.stdout || result.stderr || '').slice(0, 400) });
    }

    const pyFiles = files.filter((file) => file.endsWith('.py'));
    for (const file of pyFiles) {
        const result = await spawnAsync('python', ['-m', 'py_compile', file], { cwd: projectDir });
        const ok = result.code === 0;
        checks.push({ file: path.relative(projectDir, file), check: 'py_compile', ok, output: (result.stdout || result.stderr || '').slice(0, 400) });
    }

    const htmlExists = files.some((file) => file.endsWith('.html'));
    checks.push({ file: 'index.html', check: 'presence', ok: htmlExists, output: htmlExists ? 'index.html found' : 'index.html missing' });

    return { ok: checks.every((item) => item.ok), checks };
}

export async function buildProjectFromRequest(query, ctx = {}) {
    const text = String(query || '').trim();
    if (!text) {
        return { status: 'blocked', reason: 'طلب البناء فارغ', project_name: null, directory: null };
    }
    if (!projectIntentRegex.test(text) || !projectTopicRegex.test(text)) {
        return { status: 'not_project_build', reason: 'هذا الطلب ليس طلب بناء مشروع', project_name: null, directory: null };
    }

    const rootDir = ctx.rootDir || process.cwd();
    const projectType = inferProjectType(text);
    const baseDir = baseBuiltProjectsDir(rootDir);
    fs.mkdirSync(baseDir, { recursive: true });

    const sourceName = extractProjectName(text).replace(/[\s\r\n]+/g, ' ').slice(0, 40);
    const projectName = slugify(sourceName || 'suras-project');
    const projectDir = path.join(baseDir, `${projectName}_${Date.now()}`);
    fs.mkdirSync(projectDir, { recursive: true });

    // Ollama 1.5b is more reliable when it generates one self-contained
    // document. Gemini keeps the richer multi-file generation path.
    let provider = String(process.env.AI_PROVIDER || '').trim().toLowerCase();
    if (!provider) {
        try {
            const envText = fs.readFileSync(path.join(__dirname, '..', '.env.env'), 'utf8');
            const match = envText.match(/^\s*AI_PROVIDER\s*=\s*([^\r\n#]+)/m);
            provider = match ? match[1].trim().replace(/^["']|["']$/g, '').toLowerCase() : 'ollama';
        } catch (_) {
            provider = 'ollama';
        }
    }

    // ─── Generate the primary HTML document ───
    const debugPath = path.join(baseDir, 'debug_cloudbridge.txt');
    let generatedFiles = [];

    const siteContext = `المستخدم طلب: "${text}"

قواعد التصميم:
1. إذا ذُكر موقع أو ماركة حقيقية (أمازون، نتفليكس، نايكي، آبل...) فأنشئ صفحة هبوط مستوحاة من هويتها البصرية فقط — لا تنسخ تصميمها الفعلي ولا هيكلها.
2. اخترع محتوى أصيلاً (منتجات، مزايا، تقييمات خيالية) ولا تستخدم بيانات الموقع الحقيقي.
3. استخدم نظام ألوان الماركة وخطوطها كمرجع بصري فقط.`;

    // ── 1. Generate self-contained HTML with Tailwind CDN ──
    const htmlPrompt = `${siteContext}

أنشئ ملف index.html كاملاً ومكتفياً بذاته تماماً. المتطلبات الإلزامية:
- أدرج Tailwind CSS عبر CDN في <head>: <script src="https://cdn.tailwindcss.com"></script>
- أدرج خط Google Fonts عربي في <head> (مثل Cairo أو Tajawal)
- جميع التنسيقات INLINE فقط (Tailwind classes + وسم <style> داخل الملف) — ممنوع منعاً باتاً أي <link rel="stylesheet"> لملف خارجي
- جميع JavaScript داخل وسم <script> في نهاية الملف — ممنوع منعاً باتاً أي <script src="..."> لملف خارجي
- استخدم صور placeholder شغّالة: https://picsum.photos/seed/KEYWORD/WIDTH/HEIGHT (استبدل KEYWORD بكلمة وصفية)
- اللغة العربية مع dir="rtl" و lang="ar"
- الأقسام المطلوبة: navbar + hero + مزايا (3 بطاقات) + شبكة منتجات (4-6 عناصر) + تقييمات عملاء + CTA + footer
- تصميم فاخر، حديث، ومتجاوب مع الجوال
- أخرج HTML خام فقط — بلا backticks ولا أي شرح.`;

    const htmlResp = await cloudBridge(htmlPrompt, '', 'code', 90000);

    // ── 2. Generate CSS (اختياري — تعزيز للتنسيقات الإضافية) ──
    const cssPrompt = `${siteContext}

أنشئ ملف styles.css اختيارياً لتعزيز التنسيقات:
- تأثيرات hover ناعمة وانتقالات سلسة
- متغيرات CSS لألوان الماركة
- استجابة كاملة مع media queries
- أخرج CSS خام فقط — بلا backticks ولا شرح.`;

    let cssResp = null;

    // ── 3. Generate JS (اختياري — تفاعلية إضافية) ──
    const jsPrompt = `${siteContext}

أنشئ ملف app.js اختيارياً لتفاعلية إضافية:
- سلوك navbar عند التمرير، قائمة متنقلة للجوال
- JavaScript خالص فقط — بلا مكتبات خارجية
- أخرج JS خام فقط — بلا backticks ولا شرح.`;

    let jsResp = null;
    if (provider === 'gemini') {
        cssResp = await cloudBridge(cssPrompt, '', 'code', 60000);
        jsResp = await cloudBridge(jsPrompt, '', 'code', 45000);
    }

    // ── Debug log ──
    fs.writeFileSync(debugPath, JSON.stringify({
        timestamp: new Date().toISOString(),
        query: text,
        htmlLen: htmlResp?.text?.length || 0,
        cssLen:  cssResp?.text?.length || 0,
        jsLen:   jsResp?.text?.length || 0,
        htmlPreview: htmlResp?.text?.slice(0, 300) || 'NULL',
        cssPreview:  cssResp?.text?.slice(0, 100) || 'NULL',
    }, null, 2));

    // ── Strip markdown fences if AI added them anyway ──
    function stripFence(code = '') {
        return code.trim()
            .replace(/^```[a-zA-Z]*\r?\n?/, '')
            .replace(/\r?\n?```$/, '')
            .trim();
    }

    // ── Repair truncated HTML so it always renders ──
    function repairHtml(html = '') {
        html = html.trim();
        if (!html) return html;

        // ✅ تأكد أن Tailwind CDN موجود دائماً
        if (!html.includes('tailwindcss') && !html.includes('tailwind.min.css')) {
            const tw = '<script src="https://cdn.tailwindcss.com"></script>';
            html = html.includes('</head>')
                ? html.replace('</head>', `${tw}\n</head>`)
                : tw + '\n' + html;
        }

        // ✅ أزل روابط الملفات الخارجية (styles.css / app.js) حتى لا تظهر أخطاء 404
        // الصفحة مكتفية ذاتياً بـ Tailwind + inline styles/scripts
        html = html.replace(/<link[^>]+rel=["']stylesheet["'][^>]+href=["'][^"']*styles\.css["'][^>]*\/?>/gi, '');
        html = html.replace(/<script[^>]+src=["'][^"']*app\.js["'][^>]*><\/script>/gi, '');

        // ✅ أغلق HTML المبتور
        if (!html.includes('</body>')) html += '\n</body>';
        if (!html.includes('</html>')) html += '\n</html>';
        return html;
    }

    if (htmlResp?.text) {
        const html = repairHtml(stripFence(htmlResp.text));
        writeFileSafe(path.join(projectDir, 'index.html'), html);
        generatedFiles.push(path.join(projectDir, 'index.html'));
    }
    if (cssResp?.text) {
        writeFileSafe(path.join(projectDir, 'styles.css'), stripFence(cssResp.text));
        generatedFiles.push(path.join(projectDir, 'styles.css'));
    }
    if (jsResp?.text) {
        writeFileSafe(path.join(projectDir, 'app.js'), stripFence(jsResp.text));
        generatedFiles.push(path.join(projectDir, 'app.js'));
    }

    if (generatedFiles.length === 0) {
        fs.appendFileSync(debugPath, '\n\nFALLING BACK TO HARDCODED!');
        generatedFiles = projectFilesByType(projectType, projectName, projectDir, text);
    } else {
        fs.appendFileSync(debugPath, `\n\nSUCCESS: ${generatedFiles.length} files written`);
    }
    
    const verification = await verifyProject(projectDir);
    const previewPath = path.join(projectDir, 'index.html');
    const previewUrl = fs.existsSync(previewPath)
        ? `http://localhost:3001/preview-file?path=${encodeURIComponent(previewPath)}`
        : null;

    return {
        status: 'ok',
        project_name: projectName,
        project_type: projectType,
        directory: projectDir,
        generated_files: generatedFiles,
        verification,
        preview_url: previewUrl,
        stages: [
            'analyze_request',
            'plan_project',
            'generate_files',
            'verify_project',
            'report_results',
        ],
    };
}

export const PROJECT_ENGINE_TOOL = {
    name: 'project-engine',
    description: 'محرك بناء المشروع الحقيقي: تحليل الطلب، إنشاء بنية المشروع، كتابة الملفات، والتحقق.',
    searchHint: 'أنشئ مشروع، build project, generate app, create website',
    keywords: [
        { term: 'مشروع', weight: 4 },
        { term: 'project', weight: 4 },
        { term: 'أنشئ', weight: 5 },
        { term: 'create', weight: 4 },
        { term: 'build', weight: 3 },
        { term: 'generate', weight: 3 },
        { term: 'موقع', weight: 3 },
        { term: 'واجهة', weight: 3 },
        { term: 'تطبيق', weight: 3 },
        { term: 'api', weight: 3 },
    ],
    threshold: 5,
    timeoutMs: 300000,

    matches(query) {
        const text = String(query || '');
        if (!projectIntentRegex.test(text) || !projectTopicRegex.test(text)) return null;
        return { score: 12 };
    },

    async run(query, ctx = {}) {
        const result = await buildProjectFromRequest(query, ctx);
        if (result.status !== 'ok') {
            return [`[Project Engine] الطلب ليس طلب بناء مشروع صريحاً، أو أنه فارغ.`];
        }

        const lines = [
            `[Project Engine] بدأ بناء المشروع "${result.project_name}" (${result.project_type})`,
            `المرحلة 1: تحليل الطلب`,
            `المرحلة 2: إنشاء هيكل المشروع داخل ${result.directory}`,
            `المرحلة 3: كتابة ملفات المشروع (${result.generated_files.length} ملف)`,
            `المرحلة 4: التحقق: ${result.verification.ok ? 'نجح' : 'هناك أخطاء تحتاج مراجعة'}`,
            `المسار: ${result.directory}`,
        ];

        if (result.preview_url) lines.push(`المعاينة: ${result.preview_url}`);
        for (const check of result.verification.checks) {
            lines.push(`- ${check.file}: ${check.ok ? 'OK' : 'FAIL'} — ${check.check}`);
        }

        return lines;
    },
};
